config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :links
  resources :views, path: true
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  validates :url, presence: true
  has_many :views, dependent: :destroy

  scope :recent_first, -> { order(created_at: :desc) }

  def self.find(id)
    super ShortCode.decode(id)
  end

  def to_params
    ShortCode.encode(id)
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABETS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze

  BASE = ALPHABETS.length

  def self.encode(number)
    return ALPHABETS.first if number.zero? || number.nil?

    result = ""

    while number.positive?
      index = number % BASE
      char = ALPHABETS[index]
      result.prepend(char)
      number /= BASE
    end

    result
  end

  def self.decode(string)
    number = 0

    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABETS.index(char)
      number += index * power
    end

    number
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[show]

  def index
    @links = Link.recent_first
  end

  def show
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_path
    else
      index
      redirect_to :index, status: :unprocessable_entity
    end
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(
      :url
    )
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link, only: %i[show]

  def show
    @link.views.create!(ip: request.ip, user_agent: request.user_agent)
    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= link_to link.to_param, link %>
  <%= link.url %>
  <%= pluralize link.views_count, "views" %>

  <%= link_to view_path(link), target: :_blank, data: { turbo: false } do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
    </svg>
  <% end %>
<% end %>

app/views/links/index.html.erb
<h1>URL Shortner</h1>
<%= form_with model: Link.new do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, required: true, autofocus: true, placeholder: 'https://example.com', class: 'flex-grow rounded' %>
    <%= form.button 'Save', class: 'px-3 py-2 rounded bg-gray-200 hover:bg-gray-400 hover:text-white' %>
  </div>
<% end %>

<%= render @links %>

app/views/links/show.html.erb
<div>
  <h1><%= @link.url %></h1>
  <%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>
</div>